# Init

In [1]:
import pandas as pd

# Data Cleaning Quali

In [2]:
jed24_q = pd.read_csv('saudi24_quali_laps.csv')
jed24_q

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:21:50.987000,VER,1,NaN,1.0,1.0,0 days 00:20:12.226000,NaN,NaN,0 days 00:00:31.105000,...,True,Red Bull Racing,0 days 00:20:12.226000,2024-03-08 17:06:16.988,1,NaN,False,NaN,False,False
1,0 days 00:23:19.478000,VER,1,0 days 00:01:28.491000,2.0,1.0,NaN,NaN,0 days 00:00:32.081000,0 days 00:00:28.013000,...,True,Red Bull Racing,0 days 00:21:50.987000,2024-03-08 17:07:55.749,1,NaN,False,NaN,False,True
2,0 days 00:25:25.315000,VER,1,0 days 00:02:05.837000,3.0,1.0,NaN,0 days 00:25:23.773000,0 days 00:00:43.178000,0 days 00:00:39.436000,...,True,Red Bull Racing,0 days 00:23:19.478000,2024-03-08 17:09:24.240,1,NaN,False,NaN,False,False
3,0 days 00:29:59.456000,VER,1,NaN,4.0,2.0,0 days 00:28:08.503000,NaN,NaN,0 days 00:00:31.857000,...,False,Red Bull Racing,0 days 00:25:25.315000,2024-03-08 17:11:30.077,1,NaN,False,NaN,False,False
4,0 days 00:31:27.627000,VER,1,0 days 00:01:28.171000,5.0,2.0,NaN,NaN,0 days 00:00:31.953000,0 days 00:00:27.991000,...,False,Red Bull Racing,0 days 00:29:59.456000,2024-03-08 17:16:04.218,1,NaN,False,NaN,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,0 days 00:23:10.820000,SAR,2,0 days 00:01:29.540000,5.0,1.0,NaN,NaN,0 days 00:00:32.594000,0 days 00:00:28.393000,...,True,Williams,0 days 00:21:41.280000,2024-03-08 17:07:46.042,1,NaN,False,NaN,False,True
312,0 days 00:25:11.492000,SAR,2,0 days 00:02:00.672000,6.0,1.0,NaN,0 days 00:25:10.424000,0 days 00:00:41.105000,0 days 00:00:36.446000,...,True,Williams,0 days 00:23:10.820000,2024-03-08 17:09:15.582,1,NaN,False,NaN,False,False
313,0 days 00:29:14.374000,SAR,2,NaN,7.0,2.0,0 days 00:27:17.863000,NaN,NaN,0 days 00:00:32.897000,...,True,Williams,0 days 00:25:11.492000,2024-03-08 17:11:16.254,1,NaN,False,NaN,False,False
314,0 days 00:30:43.900000,SAR,2,0 days 00:01:29.526000,8.0,2.0,NaN,NaN,0 days 00:00:32.691000,0 days 00:00:28.383000,...,True,Williams,0 days 00:29:14.374000,2024-03-08 17:15:19.136,1,NaN,False,NaN,False,True
315,0 days 00:32:54.958000,SAR,2,0 days 00:02:11.058000,9.0,2.0,NaN,0 days 00:32:53.880000,0 days 00:00:57.071000,0 days 00:00:33.217000,...,True,Williams,0 days 00:30:43.900000,2024-03-08 17:16:48.662,1,NaN,False,NaN,False,False

## Picking Data

In [3]:
df1_jed24_q = jed24_q[['Driver', 'DriverNumber', 
                       'LapNumber','Stint', 'LapTime',
                       'Sector1Time', 'Sector2Time', 'Sector3Time',
                       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST',
                       'Compound', 'TyreLife', 'FreshTyre',
                       'Deleted']]
df1_jed24_q

,Driver,DriverNumber,LapNumber,Stint,LapTime,Sector1Time,Sector2Time,Sector3Time,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,Deleted
0,VER,1,1.0,1.0,NaN,NaN,0 days 00:00:31.105000,0 days 00:00:32.698000,277.0,284.0,309.0,254.0,SOFT,1.0,True,False
1,VER,1,2.0,1.0,0 days 00:01:28.491000,0 days 00:00:32.081000,0 days 00:00:28.013000,0 days 00:00:28.397000,295.0,326.0,306.0,330.0,SOFT,2.0,True,False
2,VER,1,3.0,1.0,0 days 00:02:05.837000,0 days 00:00:43.178000,0 days 00:00:39.436000,0 days 00:00:43.223000,248.0,193.0,NaN,230.0,SOFT,3.0,True,False
3,VER,1,4.0,2.0,NaN,NaN,0 days 00:00:31.857000,0 days 00:00:40.015000,271.0,290.0,309.0,137.0,SOFT,4.0,False,False
4,VER,1,5.0,2.0,0 days 00:01:28.171000,0 days 00:00:31.953000,0 days 00:00:27.991000,0 days 00:00:28.227000,294.0,327.0,307.0,333.0,SOFT,5.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,SAR,2,5.0,1.0,0 days 00:01:29.540000,0 days 00:00:32.594000,0 days 00:00:28.393000,0 days 00:00:28.553000,290.0,325.0,304.0,329.0,SOFT,5.0,True,False
312,SAR,2,6.0,1.0,0 days 00:02:00.672000,0 days 00:00:41.105000,0 days 00:00:36.446000,0 days 00:00:43.121000,228.0,247.0,NaN,229.0,SOFT,6.0,True,False
313,SAR,2,7.0,2.0,NaN,NaN,0 days 00:00:32.897000,0 days 00:00:32.584000,280.0,299.0,307.0,288.0,SOFT,1.0,True,False
314,SAR,2,8.0,2.0,0 days 00:01:29.526000,0 days 00:00:32.691000,0 days 00:00:28.383000,0 days 00:00:28.452000,287.0,325.0,307.0,330.0,SOFT,2.0,True,False
315,SAR,2,9.0,2.0,0 days 00:02:11.058000,0 days 00:00:57.071000,0 days 00:00:33.217000,0 days 00:00:40.770000,263.0,226.0,NaN,243.0,SOFT,3.0,True,False

## Convert to seconds

In [4]:
# Convert string representations of time to Timedelta objects
df1_jed24_q['LapTime'] = pd.to_timedelta(df1_jed24_q['LapTime'])
df1_jed24_q['Sector1Time'] = pd.to_timedelta(df1_jed24_q['Sector1Time'])
df1_jed24_q['Sector2Time'] = pd.to_timedelta(df1_jed24_q['Sector2Time'])
df1_jed24_q['Sector3Time'] = pd.to_timedelta(df1_jed24_q['Sector3Time'])

# Now convert the Timedelta objects to seconds
df1_jed24_q['LapTime'] = df1_jed24_q['LapTime'].dt.total_seconds()
df1_jed24_q['Sector1Time'] = df1_jed24_q['Sector1Time'].dt.total_seconds()
df1_jed24_q['Sector2Time'] = df1_jed24_q['Sector2Time'].dt.total_seconds()
df1_jed24_q['Sector3Time'] = df1_jed24_q['Sector3Time'].dt.total_seconds()

df1_jed24_q

C:\Users\arkan\AppData\Local\Temp\ipykernel_7920\354330514.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_jed24_q['LapTime'] = pd.to_timedelta(df1_jed24_q['LapTime'])
C:\Users\arkan\AppData\Local\Temp\ipykernel_7920\354330514.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_jed24_q['Sector1Time'] = pd.to_timedelta(df1_jed24_q['Sector1Time'])
C:\Users\arkan\AppData\Local\Temp\ipykernel_7920\354330514.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_jed24_q['Sector2Time'] = pd.to_timedelta(df1_jed24_q['Sector2Time'])
C:\Users\arkan\AppData\Local\Temp\ipykernel_7920\354330514.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_jed24_q['Sector3Time'] = pd.to_timedelta(df1_jed24_q['Sector3Time'])
C:\Users\arkan\AppData\Local\Temp\ipykernel_7920\354330514.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_jed24_q['LapTime'] = df1_jed24_q['LapTime'].dt.total_seconds()
C:\Users\arkan\AppData\Local\Temp\ipykernel_7920\354330514.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_jed24_q['Sector1Time'] = df1_jed24_q['Sector1Time'].dt.total_seconds()
C:\Users\arkan\AppData\Local\Temp\ipykernel_7920\354330514.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_jed24_q['Sector2Time'] = df1_jed24_q['Sector2Time'].dt.total_seconds()
C:\Users\arkan\AppData\Local\Temp\ipykernel_7920\354330514.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_jed24_q['Sector3Time'] = df1_jed24_q['Sector3Time'].dt.total_seconds()

,Driver,DriverNumber,LapNumber,Stint,LapTime,Sector1Time,Sector2Time,Sector3Time,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,Deleted
0,VER,1,1.0,1.0,NaN,NaN,31.105,32.698,277.0,284.0,309.0,254.0,SOFT,1.0,True,False
1,VER,1,2.0,1.0,88.491,32.081,28.013,28.397,295.0,326.0,306.0,330.0,SOFT,2.0,True,False
2,VER,1,3.0,1.0,125.837,43.178,39.436,43.223,248.0,193.0,NaN,230.0,SOFT,3.0,True,False
3,VER,1,4.0,2.0,NaN,NaN,31.857,40.015,271.0,290.0,309.0,137.0,SOFT,4.0,False,False
4,VER,1,5.0,2.0,88.171,31.953,27.991,28.227,294.0,327.0,307.0,333.0,SOFT,5.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,SAR,2,5.0,1.0,89.540,32.594,28.393,28.553,290.0,325.0,304.0,329.0,SOFT,5.0,True,False
312,SAR,2,6.0,1.0,120.672,41.105,36.446,43.121,228.0,247.0,NaN,229.0,SOFT,6.0,True,False
313,SAR,2,7.0,2.0,NaN,NaN,32.897,32.584,280.0,299.0,307.0,288.0,SOFT,1.0,True,False
314,SAR,2,8.0,2.0,89.526,32.691,28.383,28.452,287.0,325.0,307.0,330.0,SOFT,2.0,True,False
315,SAR,2,9.0,2.0,131.058,57.071,33.217,40.770,263.0,226.0,NaN,243.0,SOFT,3.0,True,False

In [5]:
df1_jed24_q.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316 entries, 0 to 315
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Driver        316 non-null    object
 1   DriverNumber  316 non-null    int64
 2   LapNumber     316 non-null    float64
 3   Stint         316 non-null    float64
 4   LapTime       214 non-null    float64
 5   Sector1Time   218 non-null    float64
 6   Sector2Time   308 non-null    float64
 7   Sector3Time   305 non-null    float64
 8   SpeedI1       310 non-null    float64
 9   SpeedI2       308 non-null    float64
 10  SpeedFL       223 non-null    float64
 11  SpeedST       309 non-null    float64
 12  Compound      316 non-null    object
 13  TyreLife      316 non-null    float64
 14  FreshTyre     316 non-null    bool
 15  Deleted       316 non-null    bool
dtypes: bool(2), float64(11), int64(1), object(2)
memory usage: 35.3+ KB

## Cleaning

In [6]:
df2_jed24_q = df1_jed24_q[df1_jed24_q['LapTime'].notna()]
df2_jed24_q

,Driver,DriverNumber,LapNumber,Stint,LapTime,Sector1Time,Sector2Time,Sector3Time,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,Deleted
1,VER,1,2.0,1.0,88.491,32.081,28.013,28.397,295.0,326.0,306.0,330.0,SOFT,2.0,True,False
2,VER,1,3.0,1.0,125.837,43.178,39.436,43.223,248.0,193.0,NaN,230.0,SOFT,3.0,True,False
4,VER,1,5.0,2.0,88.171,31.953,27.991,28.227,294.0,327.0,307.0,333.0,SOFT,5.0,False,False
5,VER,1,6.0,2.0,109.554,38.233,32.956,38.365,262.0,239.0,NaN,244.0,SOFT,6.0,False,False
7,VER,1,8.0,3.0,88.078,31.976,28.053,28.049,293.0,327.0,308.0,329.0,SOFT,2.0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,SAR,2,4.0,1.0,124.504,50.006,37.481,37.017,264.0,286.0,308.0,287.0,SOFT,4.0,True,False
311,SAR,2,5.0,1.0,89.540,32.594,28.393,28.553,290.0,325.0,304.0,329.0,SOFT,5.0,True,False
312,SAR,2,6.0,1.0,120.672,41.105,36.446,43.121,228.0,247.0,NaN,229.0,SOFT,6.0,True,False
314,SAR,2,8.0,2.0,89.526,32.691,28.383,28.452,287.0,325.0,307.0,330.0,SOFT,2.0,True,False
315,SAR,2,9.0,2.0,131.058,57.071,33.217,40.770,263.0,226.0,NaN,243.0,SOFT,3.0,True,False

In [7]:
df3_jed24_q = df2_jed24_q[df1_jed24_q['SpeedFL'].notna()]
df3_jed24_q

C:\Users\arkan\AppData\Local\Temp\ipykernel_7920\1783492607.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3_jed24_q = df2_jed24_q[df1_jed24_q['SpeedFL'].notna()]

,Driver,DriverNumber,LapNumber,Stint,LapTime,Sector1Time,Sector2Time,Sector3Time,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,Deleted
1,VER,1,2.0,1.0,88.491,32.081,28.013,28.397,295.0,326.0,306.0,330.0,SOFT,2.0,True,False
4,VER,1,5.0,2.0,88.171,31.953,27.991,28.227,294.0,327.0,307.0,333.0,SOFT,5.0,False,False
7,VER,1,8.0,3.0,88.078,31.976,28.053,28.049,293.0,327.0,308.0,329.0,SOFT,2.0,True,False
10,VER,1,11.0,4.0,88.033,31.892,28.035,28.106,295.0,327.0,309.0,331.0,SOFT,5.0,False,False
13,VER,1,14.0,5.0,87.472,31.763,27.800,27.909,294.0,326.0,306.0,330.0,SOFT,2.0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308,SAR,2,2.0,1.0,89.696,32.770,28.376,28.550,290.0,324.0,304.0,332.0,SOFT,2.0,True,False
309,SAR,2,3.0,1.0,126.980,50.530,40.872,35.578,239.0,235.0,275.0,285.0,SOFT,3.0,True,False
310,SAR,2,4.0,1.0,124.504,50.006,37.481,37.017,264.0,286.0,308.0,287.0,SOFT,4.0,True,False
311,SAR,2,5.0,1.0,89.540,32.594,28.393,28.553,290.0,325.0,304.0,329.0,SOFT,5.0,True,False
314,SAR,2,8.0,2.0,89.526,32.691,28.383,28.452,287.0,325.0,307.0,330.0,SOFT,2.0,True,False

## Select every driver who went under 100s (actual outlap)

In [8]:
df4_jed24_q = df3_jed24_q[df3_jed24_q['LapTime'] <= 90.0]
df4_jed24_q

,Driver,DriverNumber,LapNumber,Stint,LapTime,Sector1Time,Sector2Time,Sector3Time,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,Deleted
1,VER,1,2.0,1.0,88.491,32.081,28.013,28.397,295.0,326.0,306.0,330.0,SOFT,2.0,True,False
4,VER,1,5.0,2.0,88.171,31.953,27.991,28.227,294.0,327.0,307.0,333.0,SOFT,5.0,False,False
7,VER,1,8.0,3.0,88.078,31.976,28.053,28.049,293.0,327.0,308.0,329.0,SOFT,2.0,True,False
10,VER,1,11.0,4.0,88.033,31.892,28.035,28.106,295.0,327.0,309.0,331.0,SOFT,5.0,False,False
13,VER,1,14.0,5.0,87.472,31.763,27.800,27.909,294.0,326.0,306.0,330.0,SOFT,2.0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,BOT,77,4.0,1.0,89.634,32.823,28.361,28.450,291.0,326.0,304.0,329.0,SOFT,4.0,True,False
302,BOT,77,7.0,2.0,89.179,32.479,28.341,28.359,291.0,326.0,306.0,328.0,SOFT,2.0,True,False
308,SAR,2,2.0,1.0,89.696,32.770,28.376,28.550,290.0,324.0,304.0,332.0,SOFT,2.0,True,False
311,SAR,2,5.0,1.0,89.540,32.594,28.393,28.553,290.0,325.0,304.0,329.0,SOFT,5.0,True,False
314,SAR,2,8.0,2.0,89.526,32.691,28.383,28.452,287.0,325.0,307.0,330.0,SOFT,2.0,True,False

In [9]:
# Calculate the fastest lap time
fastest_lap_time = df3_jed24_q['LapTime'].min()

# Calculate 110% of the fastest lap time
one_ten_percent_fastest = 1.10 * fastest_lap_time

# Filter out every driver who did within 110% of the fastest lap time
df5_jed24_q = df3_jed24_q[df3_jed24_q['LapTime'] <= one_ten_percent_fastest]

df5_jed24_q

,Driver,DriverNumber,LapNumber,Stint,LapTime,Sector1Time,Sector2Time,Sector3Time,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,Deleted
1,VER,1,2.0,1.0,88.491,32.081,28.013,28.397,295.0,326.0,306.0,330.0,SOFT,2.0,True,False
4,VER,1,5.0,2.0,88.171,31.953,27.991,28.227,294.0,327.0,307.0,333.0,SOFT,5.0,False,False
7,VER,1,8.0,3.0,88.078,31.976,28.053,28.049,293.0,327.0,308.0,329.0,SOFT,2.0,True,False
10,VER,1,11.0,4.0,88.033,31.892,28.035,28.106,295.0,327.0,309.0,331.0,SOFT,5.0,False,False
13,VER,1,14.0,5.0,87.472,31.763,27.800,27.909,294.0,326.0,306.0,330.0,SOFT,2.0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,BOT,77,4.0,1.0,89.634,32.823,28.361,28.450,291.0,326.0,304.0,329.0,SOFT,4.0,True,False
302,BOT,77,7.0,2.0,89.179,32.479,28.341,28.359,291.0,326.0,306.0,328.0,SOFT,2.0,True,False
308,SAR,2,2.0,1.0,89.696,32.770,28.376,28.550,290.0,324.0,304.0,332.0,SOFT,2.0,True,False
311,SAR,2,5.0,1.0,89.540,32.594,28.393,28.553,290.0,325.0,304.0,329.0,SOFT,5.0,True,False
314,SAR,2,8.0,2.0,89.526,32.691,28.383,28.452,287.0,325.0,307.0,330.0,SOFT,2.0,True,False

## Join

In [10]:
df5_jed24_q

,Driver,DriverNumber,LapNumber,Stint,LapTime,Sector1Time,Sector2Time,Sector3Time,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,Deleted
1,VER,1,2.0,1.0,88.491,32.081,28.013,28.397,295.0,326.0,306.0,330.0,SOFT,2.0,True,False
4,VER,1,5.0,2.0,88.171,31.953,27.991,28.227,294.0,327.0,307.0,333.0,SOFT,5.0,False,False
7,VER,1,8.0,3.0,88.078,31.976,28.053,28.049,293.0,327.0,308.0,329.0,SOFT,2.0,True,False
10,VER,1,11.0,4.0,88.033,31.892,28.035,28.106,295.0,327.0,309.0,331.0,SOFT,5.0,False,False
13,VER,1,14.0,5.0,87.472,31.763,27.800,27.909,294.0,326.0,306.0,330.0,SOFT,2.0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,BOT,77,4.0,1.0,89.634,32.823,28.361,28.450,291.0,326.0,304.0,329.0,SOFT,4.0,True,False
302,BOT,77,7.0,2.0,89.179,32.479,28.341,28.359,291.0,326.0,306.0,328.0,SOFT,2.0,True,False
308,SAR,2,2.0,1.0,89.696,32.770,28.376,28.550,290.0,324.0,304.0,332.0,SOFT,2.0,True,False
311,SAR,2,5.0,1.0,89.540,32.594,28.393,28.553,290.0,325.0,304.0,329.0,SOFT,5.0,True,False
314,SAR,2,8.0,2.0,89.526,32.691,28.383,28.452,287.0,325.0,307.0,330.0,SOFT,2.0,True,False

In [11]:
quali = pd.read_csv('saudi24_quali_results.csv')
quali

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points
0,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671c6,red_bull,Max,Verstappen,Max Verstappen,...,NED,1.0,NaN,NaN,0 days 00:01:28.171000,0 days 00:01:28.033000,0 days 00:01:27.472000,NaN,NaN,NaN
1,16,C LECLERC,LEC,leclerc,Ferrari,e8002d,ferrari,Charles,Leclerc,Charles Leclerc,...,MON,2.0,NaN,NaN,0 days 00:01:28.318000,0 days 00:01:28.112000,0 days 00:01:27.791000,NaN,NaN,NaN
2,11,S PEREZ,PER,perez,Red Bull Racing,3671c6,red_bull,Sergio,Perez,Sergio Perez,...,MEX,3.0,NaN,NaN,0 days 00:01:28.638000,0 days 00:01:28.467000,0 days 00:01:27.807000,NaN,NaN,NaN
3,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,ESP,4.0,NaN,NaN,0 days 00:01:28.706000,0 days 00:01:28.122000,0 days 00:01:27.846000,NaN,NaN,NaN
4,81,O PIASTRI,PIA,piastri,McLaren,ff8000,mclaren,Oscar,Piastri,Oscar Piastri,...,AUS,5.0,NaN,NaN,0 days 00:01:28.755000,0 days 00:01:28.343000,0 days 00:01:28.089000,NaN,NaN,NaN
5,4,L NORRIS,NOR,norris,McLaren,ff8000,mclaren,Lando,Norris,Lando Norris,...,GBR,6.0,NaN,NaN,0 days 00:01:28.805000,0 days 00:01:28.479000,0 days 00:01:28.132000,NaN,NaN,NaN
6,63,G RUSSELL,RUS,russell,Mercedes,27f4d2,mercedes,George,Russell,George Russell,...,GBR,7.0,NaN,NaN,0 days 00:01:28.749000,0 days 00:01:28.448000,0 days 00:01:28.316000,NaN,NaN,NaN
7,44,L HAMILTON,HAM,hamilton,Mercedes,27f4d2,mercedes,Lewis,Hamilton,Lewis Hamilton,...,GBR,8.0,NaN,NaN,0 days 00:01:28.994000,0 days 00:01:28.606000,0 days 00:01:28.460000,NaN,NaN,NaN
8,22,Y TSUNODA,TSU,tsunoda,RB,6692ff,rb,Yuki,Tsunoda,Yuki Tsunoda,...,JPN,9.0,NaN,NaN,0 days 00:01:28.988000,0 days 00:01:28.564000,0 days 00:01:28.547000,NaN,NaN,NaN
9,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,CAN,10.0,NaN,NaN,0 days 00:01:28.250000,0 days 00:01:28.578000,0 days 00:01:28.572000,NaN,NaN,NaN
10,38,O BEARMAN,BEA,bearman,Ferrari,e8002d,ferrari,Oliver,Bearman,Oliver Bearman,...,GBR,11.0,NaN,NaN,0 days 00:01:28.984000,0 days 00:01:28.642000,NaN,NaN,NaN,NaN
11,23,A ALBON,ALB,albon,Williams,64c4ff,williams,Alexander,Albon,Alexander Albon,...,THA,12.0,NaN,NaN,0 days 00:01:29.107000,0 days 00:01:28.980000,NaN,NaN,NaN,NaN
12,20,K MAGNUSSEN,MAG,kevin_magnussen,Haas F1 Team,b6babd,haas,Kevin,Magnussen,Kevin Magnussen,...,DEN,13.0,NaN,NaN,0 days 00:01:29.069000,0 days 00:01:29.020000,NaN,NaN,NaN,NaN
13,3,D RICCIARDO,RIC,ricciardo,RB,6692ff,rb,Daniel,Ricciardo,Daniel Ricciardo,...,AUS,14.0,NaN,NaN,0 days 00:01:29.065000,0 days 00:01:29.025000,NaN,NaN,NaN,NaN
14,27,N HULKENBERG,HUL,hulkenberg,Haas F1 Team,b6babd,haas,Nico,Hulkenberg,Nico Hulkenberg,...,GER,15.0,NaN,NaN,0 days 00:01:29.055000,NaN,NaN,NaN,NaN,NaN
15,77,V BOTTAS,BOT,bottas,Kick Sauber,52e252,sauber,Valtteri,Bottas,Valtteri Bottas,...,FIN,16.0,NaN,NaN,0 days 00:01:29.179000,NaN,NaN,NaN,NaN,NaN
16,31,E OCON,OCO,ocon,Alpine,ff87bc,alpine,Esteban,Ocon,Esteban Ocon,...,FRA,17.0,NaN,NaN,0 days 00:01:29.475000,NaN,NaN,NaN,NaN,NaN
17,10,P GASLY,GAS,gasly,Alpine,ff87bc,alpine,Pierre,Gasly,Pierre Gasly,...,FRA,18.0,NaN,NaN,0 days 00:01:29.479000,NaN,NaN,NaN,NaN,NaN
18,2,L SARGEANT,SAR,sargeant,Williams,64c4ff,williams,Logan,Sargeant,Logan Sargeant,...,USA,19.0,NaN,NaN,0 days 00:01:29.526000,NaN,NaN,NaN,NaN,NaN
19,24,G ZHOU,ZHO,zhou,Kick Sauber,52e252,sauber,Guanyu,Zhou,Guanyu Zhou,...,CHN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
merge_df = pd.merge( df5_jed24_q, quali[['Abbreviation', 'TeamColor', 'TeamName']], left_on='Driver', right_on='Abbreviation', how='inner')
merge_df

,Driver,DriverNumber,LapNumber,Stint,LapTime,Sector1Time,Sector2Time,Sector3Time,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,Deleted,Abbreviation,TeamColor,TeamName
0,VER,1,2.0,1.0,88.491,32.081,28.013,28.397,295.0,326.0,306.0,330.0,SOFT,2.0,True,False,VER,3671c6,Red Bull Racing
1,VER,1,5.0,2.0,88.171,31.953,27.991,28.227,294.0,327.0,307.0,333.0,SOFT,5.0,False,False,VER,3671c6,Red Bull Racing
2,VER,1,8.0,3.0,88.078,31.976,28.053,28.049,293.0,327.0,308.0,329.0,SOFT,2.0,True,False,VER,3671c6,Red Bull Racing
3,VER,1,11.0,4.0,88.033,31.892,28.035,28.106,295.0,327.0,309.0,331.0,SOFT,5.0,False,False,VER,3671c6,Red Bull Racing
4,VER,1,14.0,5.0,87.472,31.763,27.800,27.909,294.0,326.0,306.0,330.0,SOFT,2.0,True,False,VER,3671c6,Red Bull Racing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,BOT,77,4.0,1.0,89.634,32.823,28.361,28.450,291.0,326.0,304.0,329.0,SOFT,4.0,True,False,BOT,52e252,Kick Sauber
91,BOT,77,7.0,2.0,89.179,32.479,28.341,28.359,291.0,326.0,306.0,328.0,SOFT,2.0,True,False,BOT,52e252,Kick Sauber
92,SAR,2,2.0,1.0,89.696,32.770,28.376,28.550,290.0,324.0,304.0,332.0,SOFT,2.0,True,False,SAR,64c4ff,Williams
93,SAR,2,5.0,1.0,89.540,32.594,28.393,28.553,290.0,325.0,304.0,329.0,SOFT,5.0,True,False,SAR,64c4ff,Williams
94,SAR,2,8.0,2.0,89.526,32.691,28.383,28.452,287.0,325.0,307.0,330.0,SOFT,2.0,True,False,SAR,64c4ff,Williams

In [13]:
df6_jed24_q = merge_df 
df6_jed24_q

,Driver,DriverNumber,LapNumber,Stint,LapTime,Sector1Time,Sector2Time,Sector3Time,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,Deleted,Abbreviation,TeamColor,TeamName
0,VER,1,2.0,1.0,88.491,32.081,28.013,28.397,295.0,326.0,306.0,330.0,SOFT,2.0,True,False,VER,3671c6,Red Bull Racing
1,VER,1,5.0,2.0,88.171,31.953,27.991,28.227,294.0,327.0,307.0,333.0,SOFT,5.0,False,False,VER,3671c6,Red Bull Racing
2,VER,1,8.0,3.0,88.078,31.976,28.053,28.049,293.0,327.0,308.0,329.0,SOFT,2.0,True,False,VER,3671c6,Red Bull Racing
3,VER,1,11.0,4.0,88.033,31.892,28.035,28.106,295.0,327.0,309.0,331.0,SOFT,5.0,False,False,VER,3671c6,Red Bull Racing
4,VER,1,14.0,5.0,87.472,31.763,27.800,27.909,294.0,326.0,306.0,330.0,SOFT,2.0,True,False,VER,3671c6,Red Bull Racing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,BOT,77,4.0,1.0,89.634,32.823,28.361,28.450,291.0,326.0,304.0,329.0,SOFT,4.0,True,False,BOT,52e252,Kick Sauber
91,BOT,77,7.0,2.0,89.179,32.479,28.341,28.359,291.0,326.0,306.0,328.0,SOFT,2.0,True,False,BOT,52e252,Kick Sauber
92,SAR,2,2.0,1.0,89.696,32.770,28.376,28.550,290.0,324.0,304.0,332.0,SOFT,2.0,True,False,SAR,64c4ff,Williams
93,SAR,2,5.0,1.0,89.540,32.594,28.393,28.553,290.0,325.0,304.0,329.0,SOFT,5.0,True,False,SAR,64c4ff,Williams
94,SAR,2,8.0,2.0,89.526,32.691,28.383,28.452,287.0,325.0,307.0,330.0,SOFT,2.0,True,False,SAR,64c4ff,Williams

## Extract CSV for Readability

In [14]:
df6_jed24_q.to_csv('jed24_q_clean.csv', index=False)

# Data Race Cleaning

In [17]:
jed24_r = pd.read_csv('saudi24_race_laps.csv')
jed24_r

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:01:19.666000,VER,1,0 days 00:01:35.505000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:29.707000,...,True,Red Bull Racing,0 days 00:59:43.836000,2024-03-09 17:03:59.056,1.0,1.0,False,NaN,False,False
1,0 days 01:02:53.871000,VER,1,0 days 00:01:34.205000,2.0,1.0,NaN,NaN,0 days 00:00:34.720000,0 days 00:00:29.628000,...,True,Red Bull Racing,0 days 01:01:19.666000,2024-03-09 17:05:34.886,1.0,1.0,False,NaN,False,True
2,0 days 01:04:27.914000,VER,1,0 days 00:01:34.043000,3.0,1.0,NaN,NaN,0 days 00:00:34.530000,0 days 00:00:29.621000,...,True,Red Bull Racing,0 days 01:02:53.871000,2024-03-09 17:07:09.091,1.0,1.0,False,NaN,False,True
3,0 days 01:06:01.668000,VER,1,0 days 00:01:33.754000,4.0,1.0,NaN,NaN,0 days 00:00:34.416000,0 days 00:00:29.541000,...,True,Red Bull Racing,0 days 01:04:27.914000,2024-03-09 17:08:43.134,1.0,1.0,False,NaN,False,True
4,0 days 01:07:35.623000,VER,1,0 days 00:01:33.955000,5.0,1.0,NaN,NaN,0 days 00:00:34.457000,0 days 00:00:29.590000,...,True,Red Bull Racing,0 days 01:06:01.668000,2024-03-09 17:10:16.888,1.0,1.0,False,NaN,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896,0 days 02:14:48.836000,PIA,81,0 days 00:01:32.557000,46.0,2.0,NaN,NaN,0 days 00:00:34.112000,0 days 00:00:29.071000,...,False,McLaren,0 days 02:13:16.279000,2024-03-09 18:17:31.499,1.0,4.0,False,NaN,False,True
897,0 days 02:16:21.410000,PIA,81,0 days 00:01:32.574000,47.0,2.0,NaN,NaN,0 days 00:00:34.006000,0 days 00:00:29.145000,...,False,McLaren,0 days 02:14:48.836000,2024-03-09 18:19:04.056,1.0,4.0,False,NaN,False,True
898,0 days 02:17:54.067000,PIA,81,0 days 00:01:32.657000,48.0,2.0,NaN,NaN,0 days 00:00:34.010000,0 days 00:00:29.151000,...,False,McLaren,0 days 02:16:21.410000,2024-03-09 18:20:36.630,1.0,4.0,False,NaN,False,True
899,0 days 02:19:26.655000,PIA,81,0 days 00:01:32.588000,49.0,2.0,NaN,NaN,0 days 00:00:34.052000,0 days 00:00:29.094000,...,False,McLaren,0 days 02:17:54.067000,2024-03-09 18:22:09.287,1.0,4.0,False,NaN,False,True
900,0 days 02:20:59.424000,PIA,81,0 days 00:01:32.769000,50.0,2.0,NaN,NaN,0 days 00:00:33.983000,0 days 00:00:29.094000,...,False,McLaren,0 days 02:19:26.655000,2024-03-09 18:23:41.875,1.0,4.0,False,NaN,False,True

## Pick Data

In [18]:
df1_jed24_r = jed24_r[['Time',
                       'Driver', 'DriverNumber', 
                       'LapNumber','Stint', 'LapTime', 'TrackStatus',
                       'PitInTime', 'PitOutTime',
                       'Sector1Time', 'Sector2Time', 'Sector3Time',
                       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST',
                       'Compound', 'TyreLife', 'FreshTyre'
                      ]]
df1_jed24_r

,Time,Driver,DriverNumber,LapNumber,Stint,LapTime,TrackStatus,PitInTime,PitOutTime,Sector1Time,Sector2Time,Sector3Time,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre
0,0 days 01:01:19.666000,VER,1,1.0,1.0,0 days 00:01:35.505000,1.0,NaN,NaN,NaN,0 days 00:00:29.707000,0 days 00:00:29.830000,284.0,294.0,290.0,298.0,MEDIUM,1.0,True
1,0 days 01:02:53.871000,VER,1,2.0,1.0,0 days 00:01:34.205000,1.0,NaN,NaN,0 days 00:00:34.720000,0 days 00:00:29.628000,0 days 00:00:29.857000,NaN,296.0,291.0,302.0,MEDIUM,2.0,True
2,0 days 01:04:27.914000,VER,1,3.0,1.0,0 days 00:01:34.043000,1.0,NaN,NaN,0 days 00:00:34.530000,0 days 00:00:29.621000,0 days 00:00:29.892000,285.0,296.0,292.0,302.0,MEDIUM,3.0,True
3,0 days 01:06:01.668000,VER,1,4.0,1.0,0 days 00:01:33.754000,1.0,NaN,NaN,0 days 00:00:34.416000,0 days 00:00:29.541000,0 days 00:00:29.797000,NaN,298.0,292.0,303.0,MEDIUM,4.0,True
4,0 days 01:07:35.623000,VER,1,5.0,1.0,0 days 00:01:33.955000,1.0,NaN,NaN,0 days 00:00:34.457000,0 days 00:00:29.590000,0 days 00:00:29.908000,284.0,296.0,292.0,302.0,MEDIUM,5.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896,0 days 02:14:48.836000,PIA,81,46.0,2.0,0 days 00:01:32.557000,1.0,NaN,NaN,0 days 00:00:34.112000,0 days 00:00:29.071000,0 days 00:00:29.374000,289.0,302.0,296.0,305.0,HARD,40.0,False
897,0 days 02:16:21.410000,PIA,81,47.0,2.0,0 days 00:01:32.574000,1.0,NaN,NaN,0 days 00:00:34.006000,0 days 00:00:29.145000,0 days 00:00:29.423000,291.0,304.0,294.0,307.0,HARD,41.0,False
898,0 days 02:17:54.067000,PIA,81,48.0,2.0,0 days 00:01:32.657000,1.0,NaN,NaN,0 days 00:00:34.010000,0 days 00:00:29.151000,0 days 00:00:29.496000,290.0,309.0,295.0,311.0,HARD,42.0,False
899,0 days 02:19:26.655000,PIA,81,49.0,2.0,0 days 00:01:32.588000,1.0,NaN,NaN,0 days 00:00:34.052000,0 days 00:00:29.094000,0 days 00:00:29.442000,NaN,307.0,295.0,307.0,HARD,43.0,False
900,0 days 02:20:59.424000,PIA,81,50.0,2.0,0 days 00:01:32.769000,1.0,NaN,NaN,0 days 00:00:33.983000,0 days 00:00:29.094000,0 days 00:00:29.692000,NaN,307.0,294.0,311.0,HARD,44.0,False

## Clean Pit Time

In [19]:
df1_jed24_r['PitTime'] = df1_jed24_r.apply(
    lambda x: x['PitInTime'] if pd.notnull(x['PitInTime']) else x['PitOutTime'], axis=1
)
df1_jed24_r

C:\Users\arkan\AppData\Local\Temp\ipykernel_27012\20267722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_jed24_r['PitTime'] = df1_jed24_r.apply(

,Time,Driver,DriverNumber,LapNumber,Stint,LapTime,TrackStatus,PitInTime,PitOutTime,Sector1Time,Sector2Time,Sector3Time,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,PitTime
0,0 days 01:01:19.666000,VER,1,1.0,1.0,0 days 00:01:35.505000,1.0,NaN,NaN,NaN,0 days 00:00:29.707000,0 days 00:00:29.830000,284.0,294.0,290.0,298.0,MEDIUM,1.0,True,NaN
1,0 days 01:02:53.871000,VER,1,2.0,1.0,0 days 00:01:34.205000,1.0,NaN,NaN,0 days 00:00:34.720000,0 days 00:00:29.628000,0 days 00:00:29.857000,NaN,296.0,291.0,302.0,MEDIUM,2.0,True,NaN
2,0 days 01:04:27.914000,VER,1,3.0,1.0,0 days 00:01:34.043000,1.0,NaN,NaN,0 days 00:00:34.530000,0 days 00:00:29.621000,0 days 00:00:29.892000,285.0,296.0,292.0,302.0,MEDIUM,3.0,True,NaN
3,0 days 01:06:01.668000,VER,1,4.0,1.0,0 days 00:01:33.754000,1.0,NaN,NaN,0 days 00:00:34.416000,0 days 00:00:29.541000,0 days 00:00:29.797000,NaN,298.0,292.0,303.0,MEDIUM,4.0,True,NaN
4,0 days 01:07:35.623000,VER,1,5.0,1.0,0 days 00:01:33.955000,1.0,NaN,NaN,0 days 00:00:34.457000,0 days 00:00:29.590000,0 days 00:00:29.908000,284.0,296.0,292.0,302.0,MEDIUM,5.0,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896,0 days 02:14:48.836000,PIA,81,46.0,2.0,0 days 00:01:32.557000,1.0,NaN,NaN,0 days 00:00:34.112000,0 days 00:00:29.071000,0 days 00:00:29.374000,289.0,302.0,296.0,305.0,HARD,40.0,False,NaN
897,0 days 02:16:21.410000,PIA,81,47.0,2.0,0 days 00:01:32.574000,1.0,NaN,NaN,0 days 00:00:34.006000,0 days 00:00:29.145000,0 days 00:00:29.423000,291.0,304.0,294.0,307.0,HARD,41.0,False,NaN
898,0 days 02:17:54.067000,PIA,81,48.0,2.0,0 days 00:01:32.657000,1.0,NaN,NaN,0 days 00:00:34.010000,0 days 00:00:29.151000,0 days 00:00:29.496000,290.0,309.0,295.0,311.0,HARD,42.0,False,NaN
899,0 days 02:19:26.655000,PIA,81,49.0,2.0,0 days 00:01:32.588000,1.0,NaN,NaN,0 days 00:00:34.052000,0 days 00:00:29.094000,0 days 00:00:29.442000,NaN,307.0,295.0,307.0,HARD,43.0,False,NaN
900,0 days 02:20:59.424000,PIA,81,50.0,2.0,0 days 00:01:32.769000,1.0,NaN,NaN,0 days 00:00:33.983000,0 days 00:00:29.094000,0 days 00:00:29.692000,NaN,307.0,294.0,311.0,HARD,44.0,False,NaN

In [20]:
df1_jed24_r.to_csv('df_jed24_r.csv', index=False)

In [21]:
df2_jed24_r = df1_jed24_r.drop(columns=['PitInTime', 'PitOutTime'])
df2_jed24_r

,Time,Driver,DriverNumber,LapNumber,Stint,LapTime,TrackStatus,Sector1Time,Sector2Time,Sector3Time,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,PitTime
0,0 days 01:01:19.666000,VER,1,1.0,1.0,0 days 00:01:35.505000,1.0,NaN,0 days 00:00:29.707000,0 days 00:00:29.830000,284.0,294.0,290.0,298.0,MEDIUM,1.0,True,NaN
1,0 days 01:02:53.871000,VER,1,2.0,1.0,0 days 00:01:34.205000,1.0,0 days 00:00:34.720000,0 days 00:00:29.628000,0 days 00:00:29.857000,NaN,296.0,291.0,302.0,MEDIUM,2.0,True,NaN
2,0 days 01:04:27.914000,VER,1,3.0,1.0,0 days 00:01:34.043000,1.0,0 days 00:00:34.530000,0 days 00:00:29.621000,0 days 00:00:29.892000,285.0,296.0,292.0,302.0,MEDIUM,3.0,True,NaN
3,0 days 01:06:01.668000,VER,1,4.0,1.0,0 days 00:01:33.754000,1.0,0 days 00:00:34.416000,0 days 00:00:29.541000,0 days 00:00:29.797000,NaN,298.0,292.0,303.0,MEDIUM,4.0,True,NaN
4,0 days 01:07:35.623000,VER,1,5.0,1.0,0 days 00:01:33.955000,1.0,0 days 00:00:34.457000,0 days 00:00:29.590000,0 days 00:00:29.908000,284.0,296.0,292.0,302.0,MEDIUM,5.0,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896,0 days 02:14:48.836000,PIA,81,46.0,2.0,0 days 00:01:32.557000,1.0,0 days 00:00:34.112000,0 days 00:00:29.071000,0 days 00:00:29.374000,289.0,302.0,296.0,305.0,HARD,40.0,False,NaN
897,0 days 02:16:21.410000,PIA,81,47.0,2.0,0 days 00:01:32.574000,1.0,0 days 00:00:34.006000,0 days 00:00:29.145000,0 days 00:00:29.423000,291.0,304.0,294.0,307.0,HARD,41.0,False,NaN
898,0 days 02:17:54.067000,PIA,81,48.0,2.0,0 days 00:01:32.657000,1.0,0 days 00:00:34.010000,0 days 00:00:29.151000,0 days 00:00:29.496000,290.0,309.0,295.0,311.0,HARD,42.0,False,NaN
899,0 days 02:19:26.655000,PIA,81,49.0,2.0,0 days 00:01:32.588000,1.0,0 days 00:00:34.052000,0 days 00:00:29.094000,0 days 00:00:29.442000,NaN,307.0,295.0,307.0,HARD,43.0,False,NaN
900,0 days 02:20:59.424000,PIA,81,50.0,2.0,0 days 00:01:32.769000,1.0,0 days 00:00:33.983000,0 days 00:00:29.094000,0 days 00:00:29.692000,NaN,307.0,294.0,311.0,HARD,44.0,False,NaN

In [22]:
df2_jed24_r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 901 entries, 0 to 900
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Time          901 non-null    object
 1   Driver        901 non-null    object
 2   DriverNumber  901 non-null    int64
 3   LapNumber     901 non-null    float64
 4   Stint         901 non-null    float64
 5   LapTime       873 non-null    object
 6   TrackStatus   900 non-null    float64
 7   Sector1Time   879 non-null    object
 8   Sector2Time   900 non-null    object
 9   Sector3Time   900 non-null    object
 10  SpeedI1       664 non-null    float64
 11  SpeedI2       900 non-null    float64
 12  SpeedFL       880 non-null    float64
 13  SpeedST       900 non-null    float64
 14  Compound      901 non-null    object
 15  TyreLife      901 non-null    float64
 16  FreshTyre     901 non-null    bool
 17  PitTime       39 non-null     object
dtypes: bool(1), float64(8), int64(1), object(8)
memory usage: 120.7+ KB

In [23]:
df2_jed24_r.to_csv('df_jed24_r.csv', index=False)

## Convert time data

In [24]:
# Define a function to convert timedelta strings to total seconds
def timedelta_to_seconds(timedelta_string):
    if pd.isnull(timedelta_string):
        return None
    td = pd.Timedelta(timedelta_string)
    return td.total_seconds()

# Convert time columns to seconds
time_columns = ['Time', 'LapTime', 'Sector1Time', 'Sector2Time', 'Sector3Time', 'PitTime']
for col in time_columns:
    df2_jed24_r[col] = df2_jed24_r[col].apply(timedelta_to_seconds)

df2_jed24_r

,Time,Driver,DriverNumber,LapNumber,Stint,LapTime,TrackStatus,Sector1Time,Sector2Time,Sector3Time,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,PitTime
0,3679.666,VER,1,1.0,1.0,95.505,1.0,NaN,29.707,29.830,284.0,294.0,290.0,298.0,MEDIUM,1.0,True,NaN
1,3773.871,VER,1,2.0,1.0,94.205,1.0,34.720,29.628,29.857,NaN,296.0,291.0,302.0,MEDIUM,2.0,True,NaN
2,3867.914,VER,1,3.0,1.0,94.043,1.0,34.530,29.621,29.892,285.0,296.0,292.0,302.0,MEDIUM,3.0,True,NaN
3,3961.668,VER,1,4.0,1.0,93.754,1.0,34.416,29.541,29.797,NaN,298.0,292.0,303.0,MEDIUM,4.0,True,NaN
4,4055.623,VER,1,5.0,1.0,93.955,1.0,34.457,29.590,29.908,284.0,296.0,292.0,302.0,MEDIUM,5.0,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896,8088.836,PIA,81,46.0,2.0,92.557,1.0,34.112,29.071,29.374,289.0,302.0,296.0,305.0,HARD,40.0,False,NaN
897,8181.410,PIA,81,47.0,2.0,92.574,1.0,34.006,29.145,29.423,291.0,304.0,294.0,307.0,HARD,41.0,False,NaN
898,8274.067,PIA,81,48.0,2.0,92.657,1.0,34.010,29.151,29.496,290.0,309.0,295.0,311.0,HARD,42.0,False,NaN
899,8366.655,PIA,81,49.0,2.0,92.588,1.0,34.052,29.094,29.442,NaN,307.0,295.0,307.0,HARD,43.0,False,NaN
900,8459.424,PIA,81,50.0,2.0,92.769,1.0,33.983,29.094,29.692,NaN,307.0,294.0,311.0,HARD,44.0,False,NaN

In [25]:
df2_jed24_r.to_csv('df_jed24_r.csv', index=False)

## Join Color

In [26]:
df2_jed24_r

,Time,Driver,DriverNumber,LapNumber,Stint,LapTime,TrackStatus,Sector1Time,Sector2Time,Sector3Time,SpeedI1,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,PitTime
0,3679.666,VER,1,1.0,1.0,95.505,1.0,NaN,29.707,29.830,284.0,294.0,290.0,298.0,MEDIUM,1.0,True,NaN
1,3773.871,VER,1,2.0,1.0,94.205,1.0,34.720,29.628,29.857,NaN,296.0,291.0,302.0,MEDIUM,2.0,True,NaN
2,3867.914,VER,1,3.0,1.0,94.043,1.0,34.530,29.621,29.892,285.0,296.0,292.0,302.0,MEDIUM,3.0,True,NaN
3,3961.668,VER,1,4.0,1.0,93.754,1.0,34.416,29.541,29.797,NaN,298.0,292.0,303.0,MEDIUM,4.0,True,NaN
4,4055.623,VER,1,5.0,1.0,93.955,1.0,34.457,29.590,29.908,284.0,296.0,292.0,302.0,MEDIUM,5.0,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896,8088.836,PIA,81,46.0,2.0,92.557,1.0,34.112,29.071,29.374,289.0,302.0,296.0,305.0,HARD,40.0,False,NaN
897,8181.410,PIA,81,47.0,2.0,92.574,1.0,34.006,29.145,29.423,291.0,304.0,294.0,307.0,HARD,41.0,False,NaN
898,8274.067,PIA,81,48.0,2.0,92.657,1.0,34.010,29.151,29.496,290.0,309.0,295.0,311.0,HARD,42.0,False,NaN
899,8366.655,PIA,81,49.0,2.0,92.588,1.0,34.052,29.094,29.442,NaN,307.0,295.0,307.0,HARD,43.0,False,NaN
900,8459.424,PIA,81,50.0,2.0,92.769,1.0,33.983,29.094,29.692,NaN,307.0,294.0,311.0,HARD,44.0,False,NaN

In [27]:
race = pd.read_csv('saudi24_race_results.csv')
race

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points
0,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671c6,red_bull,Max,Verstappen,Max Verstappen,...,NED,1.0,1,1.0,NaN,NaN,NaN,0 days 01:20:43.273000,Finished,25.0
1,11,S PEREZ,PER,perez,Red Bull Racing,3671c6,red_bull,Sergio,Perez,Sergio Perez,...,MEX,2.0,2,3.0,NaN,NaN,NaN,0 days 00:00:13.643100,Finished,18.0
2,16,C LECLERC,LEC,leclerc,Ferrari,e8002d,ferrari,Charles,Leclerc,Charles Leclerc,...,MON,3.0,3,2.0,NaN,NaN,NaN,0 days 00:00:18.639000,Finished,16.0
3,81,O PIASTRI,PIA,piastri,McLaren,ff8000,mclaren,Oscar,Piastri,Oscar Piastri,...,AUS,4.0,4,5.0,NaN,NaN,NaN,0 days 00:00:32.007000,Finished,12.0
4,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,ESP,5.0,5,4.0,NaN,NaN,NaN,0 days 00:00:35.759000,Finished,10.0
5,63,G RUSSELL,RUS,russell,Mercedes,27f4d2,mercedes,George,Russell,George Russell,...,GBR,6.0,6,7.0,NaN,NaN,NaN,0 days 00:00:39.936000,Finished,8.0
6,38,O BEARMAN,BEA,bearman,Ferrari,e8002d,ferrari,Oliver,Bearman,Oliver Bearman,...,GBR,7.0,7,11.0,NaN,NaN,NaN,0 days 00:00:42.679000,Finished,6.0
7,4,L NORRIS,NOR,norris,McLaren,ff8000,mclaren,Lando,Norris,Lando Norris,...,GBR,8.0,8,6.0,NaN,NaN,NaN,0 days 00:00:45.708000,Finished,4.0
8,44,L HAMILTON,HAM,hamilton,Mercedes,27f4d2,mercedes,Lewis,Hamilton,Lewis Hamilton,...,GBR,9.0,9,8.0,NaN,NaN,NaN,0 days 00:00:47.391000,Finished,2.0
9,27,N HULKENBERG,HUL,hulkenberg,Haas F1 Team,b6babd,haas,Nico,Hulkenberg,Nico Hulkenberg,...,GER,10.0,10,15.0,NaN,NaN,NaN,0 days 00:01:16.996000,Finished,1.0
10,23,A ALBON,ALB,albon,Williams,64c4ff,williams,Alexander,Albon,Alexander Albon,...,THA,11.0,11,12.0,NaN,NaN,NaN,0 days 00:01:28.354000,Finished,0.0
11,20,K MAGNUSSEN,MAG,kevin_magnussen,Haas F1 Team,b6babd,haas,Kevin,Magnussen,Kevin Magnussen,...,DEN,12.0,12,13.0,NaN,NaN,NaN,0 days 00:01:45.737300,Finished,0.0
12,31,E OCON,OCO,ocon,Alpine,ff87bc,alpine,Esteban,Ocon,Esteban Ocon,...,FRA,13.0,13,17.0,NaN,NaN,NaN,NaN,+1 Lap,0.0
13,22,Y TSUNODA,TSU,tsunoda,RB,6692ff,rb,Yuki,Tsunoda,Yuki Tsunoda,...,JPN,14.0,14,9.0,NaN,NaN,NaN,NaN,+1 Lap,0.0
14,2,L SARGEANT,SAR,sargeant,Williams,64c4ff,williams,Logan,Sargeant,Logan Sargeant,...,USA,15.0,15,19.0,NaN,NaN,NaN,NaN,+1 Lap,0.0
15,3,D RICCIARDO,RIC,ricciardo,RB,6692ff,rb,Daniel,Ricciardo,Daniel Ricciardo,...,AUS,16.0,16,14.0,NaN,NaN,NaN,NaN,+1 Lap,0.0
16,77,V BOTTAS,BOT,bottas,Kick Sauber,52e252,sauber,Valtteri,Bottas,Valtteri Bottas,...,FIN,17.0,17,16.0,NaN,NaN,NaN,NaN,+1 Lap,0.0
17,24,G ZHOU,ZHO,zhou,Kick Sauber,52e252,sauber,Guanyu,Zhou,Guanyu Zhou,...,CHN,18.0,18,20.0,NaN,NaN,NaN,NaN,+1 Lap,0.0
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,CAN,19.0,R,10.0,NaN,NaN,NaN,NaN,Accident,0.0
19,10,P GASLY,GAS,gasly,Alpine,ff87bc,alpine,Pierre,Gasly,Pierre Gasly,...,FRA,20.0,R,18.0,NaN,NaN,NaN,NaN,Gearbox,0.0

In [28]:
merge_df = pd.merge(df2_jed24_r, race[['Abbreviation', 'TeamColor', 'TeamName']], left_on='Driver', right_on='Abbreviation', how='inner')
merge_df

,Time,Driver,DriverNumber,LapNumber,Stint,LapTime,TrackStatus,Sector1Time,Sector2Time,Sector3Time,...,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,PitTime,Abbreviation,TeamColor,TeamName
0,3679.666,VER,1,1.0,1.0,95.505,1.0,NaN,29.707,29.830,...,294.0,290.0,298.0,MEDIUM,1.0,True,NaN,VER,3671c6,Red Bull Racing
1,3773.871,VER,1,2.0,1.0,94.205,1.0,34.720,29.628,29.857,...,296.0,291.0,302.0,MEDIUM,2.0,True,NaN,VER,3671c6,Red Bull Racing
2,3867.914,VER,1,3.0,1.0,94.043,1.0,34.530,29.621,29.892,...,296.0,292.0,302.0,MEDIUM,3.0,True,NaN,VER,3671c6,Red Bull Racing
3,3961.668,VER,1,4.0,1.0,93.754,1.0,34.416,29.541,29.797,...,298.0,292.0,303.0,MEDIUM,4.0,True,NaN,VER,3671c6,Red Bull Racing
4,4055.623,VER,1,5.0,1.0,93.955,1.0,34.457,29.590,29.908,...,296.0,292.0,302.0,MEDIUM,5.0,True,NaN,VER,3671c6,Red Bull Racing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896,8088.836,PIA,81,46.0,2.0,92.557,1.0,34.112,29.071,29.374,...,302.0,296.0,305.0,HARD,40.0,False,NaN,PIA,ff8000,McLaren
897,8181.410,PIA,81,47.0,2.0,92.574,1.0,34.006,29.145,29.423,...,304.0,294.0,307.0,HARD,41.0,False,NaN,PIA,ff8000,McLaren
898,8274.067,PIA,81,48.0,2.0,92.657,1.0,34.010,29.151,29.496,...,309.0,295.0,311.0,HARD,42.0,False,NaN,PIA,ff8000,McLaren
899,8366.655,PIA,81,49.0,2.0,92.588,1.0,34.052,29.094,29.442,...,307.0,295.0,307.0,HARD,43.0,False,NaN,PIA,ff8000,McLaren
900,8459.424,PIA,81,50.0,2.0,92.769,1.0,33.983,29.094,29.692,...,307.0,294.0,311.0,HARD,44.0,False,NaN,PIA,ff8000,McLaren

In [29]:
df3_jed24_r = merge_df 
df3_jed24_r

,Time,Driver,DriverNumber,LapNumber,Stint,LapTime,TrackStatus,Sector1Time,Sector2Time,Sector3Time,...,SpeedI2,SpeedFL,SpeedST,Compound,TyreLife,FreshTyre,PitTime,Abbreviation,TeamColor,TeamName
0,3679.666,VER,1,1.0,1.0,95.505,1.0,NaN,29.707,29.830,...,294.0,290.0,298.0,MEDIUM,1.0,True,NaN,VER,3671c6,Red Bull Racing
1,3773.871,VER,1,2.0,1.0,94.205,1.0,34.720,29.628,29.857,...,296.0,291.0,302.0,MEDIUM,2.0,True,NaN,VER,3671c6,Red Bull Racing
2,3867.914,VER,1,3.0,1.0,94.043,1.0,34.530,29.621,29.892,...,296.0,292.0,302.0,MEDIUM,3.0,True,NaN,VER,3671c6,Red Bull Racing
3,3961.668,VER,1,4.0,1.0,93.754,1.0,34.416,29.541,29.797,...,298.0,292.0,303.0,MEDIUM,4.0,True,NaN,VER,3671c6,Red Bull Racing
4,4055.623,VER,1,5.0,1.0,93.955,1.0,34.457,29.590,29.908,...,296.0,292.0,302.0,MEDIUM,5.0,True,NaN,VER,3671c6,Red Bull Racing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896,8088.836,PIA,81,46.0,2.0,92.557,1.0,34.112,29.071,29.374,...,302.0,296.0,305.0,HARD,40.0,False,NaN,PIA,ff8000,McLaren
897,8181.410,PIA,81,47.0,2.0,92.574,1.0,34.006,29.145,29.423,...,304.0,294.0,307.0,HARD,41.0,False,NaN,PIA,ff8000,McLaren
898,8274.067,PIA,81,48.0,2.0,92.657,1.0,34.010,29.151,29.496,...,309.0,295.0,311.0,HARD,42.0,False,NaN,PIA,ff8000,McLaren
899,8366.655,PIA,81,49.0,2.0,92.588,1.0,34.052,29.094,29.442,...,307.0,295.0,307.0,HARD,43.0,False,NaN,PIA,ff8000,McLaren
900,8459.424,PIA,81,50.0,2.0,92.769,1.0,33.983,29.094,29.692,...,307.0,294.0,311.0,HARD,44.0,False,NaN,PIA,ff8000,McLaren

## Extract CSV for Readability

In [30]:
df3_jed24_r.to_csv('jed24_r_clean.csv', index=False)